### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by vikts83** [GusMuche/homebridge-zipabox-platform#31]
Hello,

Have this problem, when install a plugin

[9/22/2020, 9:49:22 PM] [ZipaboxPlatform] [BOXAPI] [fstatus] Error on fstatus. Unauthorized                                                                          
[9/22/2020, 9:49:22 PM] [ZipaboxPlatform] [PTFM] [connectTheBox] Unexpexted error before security :  Error: Unauthorized                                             
    at ZipaboxApi.<anonymous> (/homebridge/node_modules/homebridge-zipabox-platform-dev/lib/zipaboxApi.js:701:16)                                                    
    at new Promise (<anonymous>)                                                                                                                                     
    at ZipaboxApi.fstatus (/homebridge/node_modules/homebridge-zipabox-platform-dev/lib/zipaboxApi.js:695:12)                                                        
    at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                              
[9/22/2020, 9:49:22 PM] [ZipaboxPlatform] [PTFM] [connectTheBox] Error on connectTheBox after security : Error: Error: Unauthorized                                  
    at ZipaPlatform.manageError (/homebridge/node_modules/homebridge-zipabox-platform-dev/lib/platform.js:118:13)                                                    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by GusMuche** [comment]
Hello,

Can you please send me a copy or code past of your config for the plugin ? I see a lot of possibilities for this issues...

Just remove passcode from your copy before paste it in a reply comment.

Regards,
