### ISSUE TITLE
Incompatibiliy issue

### ISSUE THREAD

**Issue by szepesisz** [GusMuche/homebridge-zipabox-platform#41]
Earlier I had a working version, but I had to recreate the system and I cannot get it to work.

Tried with numerous earlier versions but always getting the same error:

```
[7/12/2024, 8:00:07 PM] ERROR INITIALIZING PLUGIN homebridge-zipabox-platform:
[7/12/2024, 8:00:07 PM] TypeError: require(...) is not a function
    at Object.<anonymous> (/homebridge/node_modules/homebridge-zipabox-platform/lib/zipaboxApi.js:17:38)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-zipabox-platform/lib/platform.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[7/12/2024, 8:00:07 PM] ====================
```

If any of you who's seeing this has a working setup, please share with me the versions of the Homebridge and the plugin.

**Comment by szepesisz** [comment]
The solution was to manually install the dependencies with the correct versions 
```
npm list
fetch-cookie@0.7.3
node-fetch@2.6.0
...
```
Somehow the default installation does not no it corrrectly
